### ISSUE TITLE
IllegalArgumentException: Invalid arguments count.
And False interstitial loaded signal

### ISSUE THREAD

**Issue by syntaxerror247** [cengiz-pz/godot-android-admob-plugin#13]
Following exception is being reported in logcat after closing interstitial ad
```
java.lang.IllegalArgumentException: Invalid arguments count. Should be 2  but is 1
     at org.godotengine.godot.plugin.GodotPlugin.emitSignal(GodotPlugin.java:385)
     at org.godotengine.godot.plugin.GodotPlugin.emitSignal(GodotPlugin.java:360)
     at org.godotengine.plugin.android.admob.AdmobPlugin.access$2400(AdmobPlugin.java:58)
     at org.godotengine.plugin.android.admob.AdmobPlugin$3.onInterstitialClosed(AdmobPlugin.java:471)
     at org.godotengine.plugin.android.admob.Interstitial$1.onAdDismissedFullScreenContent(Interstitial.java:84)
     at com.google.android.gms.ads.internal.client.zzbb.zzc(com.google.android.gms:play-services-ads-lite@@23.0.0:1)
     at com.google.android.gms.ads.internal.client.zzch.zzbO(com.google.android.gms:play-services-ads-lite@@23.0.0:3)
     at com.google.android.gms.internal.ads.zzayh.onTransact(com.google.android.gms:play-services-ads-base@@23.0.0:3)
     at android.os.Binder.transact(Binder.java:1190)
```

- [x] IllegalArgumentException
- [x] False interstitial loaded signal

**Comment by cengiz-pz** [comment]
Hi @syntaxerror247, please let me know if the new release fixes this issue on your side.

**Comment by syntaxerror247** [comment]
Thanks @cengiz-pz , this issue is resolved.

But now new interstitial is loaded automatically after I close one. Is this intentional??

**Comment by cengiz-pz** [comment]
> But now new interstitial is loaded automatically after I close one. Is this intentional??

No, it is not intentional.  It is an issue with the demo app that will need to be investigated.

**Comment by syntaxerror247** [comment]
> It is an issue with the demo app that will need to be investigated.

It is not an issue with demo app, I tested it in my project and interstitial loaded signal is being emitted after closing an interstitial ad.
This is possibly a false signal because when I try to show ad, logcat clearly throws `error: ad {id} not found`

**Comment by cengiz-pz** [comment]
@syntaxerror247, it turns out that interstitial ads are automatically reloaded after they're displayed and then closed.  Now, the `interstitial_ad_loaded` signal gets emitted only upon first load & the new `interstitial_ad_refreshed` signal gets emitted upon subsequent reloads.

**Comment by syntaxerror247** [comment]
@cengiz-pz , if I load interstitial first time in my game it will emit `interstitial_ad_loaded` signal but after closing it, if I load another interstitial it will emit `interstitial_ad_refreshed`.
Or, it will only emit `interstitial_ad_refreshed` if it is automatically reloaded ??

**Comment by cengiz-pz** [comment]
@syntaxerror247
> if I load interstitial first time in my game it will emit interstitial_ad_loaded signal

Yes

> but after closing it, if I load another interstitial it will emit interstitial_ad_refreshed

No, `interstitial_ad_refreshed` signal is only emitted if Admob automatically reloads an interstitial ad that had previously been loaded.

> it will only emit interstitial_ad_refreshed if it is automatically reloaded ??

Yes, only if auto-reloaded by Admob.

**Comment by syntaxerror247** [comment]
Thanks for explaining 😀
